### ISSUE TITLE
xgo does only work with the go import path

### ISSUE THREAD

**Issue by zimmski** [karalabe/xgo#1]
I do not see a way to give xgo just a file to compile. e.g.

```
xgo path/to/a/main.go
```

**Comment by bdesham** [comment]
@kdar This is excellent, thank you!

Your example instructions are missing a `cd` command… in case it will save someone else a couple of seconds, the instructions should be

    cd $GOPATH/src
    mkdir test
    cd test
    echo -e 'package main\n import "fmt"\n func main(){\nfmt.Println("Hello")\n}' > main.go
    xgo -out "build/test" ./

**Comment by karalabe** [comment]
Had been doing some work lately requiring xgo, so I've added a lot of new features, including building local code. If instead of the import path you specify a local path (begins in either `.` or `/`), it will resolve the import path, mount in all source code found in the various GOPATH components and cross compile using all code found on the host machine. Also, it will mount every local folder as read only to ensure that no modifications are made to your local files.

The idea is based on @kdar's code, so I thank him for that, though it needed a bit of rework to enable read only filesystems and multiple GOPATH components. Hope it's useful :)

**Comment by jjhesk** [comment]
@karalabe do you have some examples to show me?
