### ISSUE TITLE
Any way to build private repositories

### ISSUE THREAD

**Issue by cpjolicoeur** [karalabe/xgo#13]
For go projects that are private on the git server (github, bitbucket, etc...).  Right now you will just get a `403 Forbidden` error when the Docker image tries to pull down the repo.

Is there any way we can add support for private repos easily?

**Comment by karalabe** [comment]
Building private repos isn't really something I've needed, nor have access to such, so I'm reluctant to try and patch it in. However, I've just release a new version which can handle building from the local host system instead of pulling from the internet, so if you have all the code already available locally, it will not pull from the internet so it should succeed building just fine :)

To specify a local build, use a relative or absolute path (i.e. start with `.` or `/`)

**Comment by jan4984** [comment]
why xgo report `Requested path invalid.` please

```
➜  cu10010 git:(master) ✗ pwd
/home/jan/go/src/code.iflyos.vip/cu10010
➜  cu10010 git:(master) ✗ ls ./cmd/entry/main.go
./cmd/entry/main.go
➜  cu10010 git:(master) ✗ GOPATH=/home/jan/go ~/go/bin/xgo -ldflags="-s -w" --targets=linux/arm7 -buildmode=c-shared ./cmd/entry/main.go
Checking docker installation...
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:20:43 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:28:38 2018
  OS/Arch:          linux/amd64
  Experimental:     false

Checking for required docker image karalabe/xgo-latest... found.
2018/10/12 14:56:42 Requested path invalid.
➜  cu10010 git:(master) ✗ 
```

**Comment by cedricve** [comment]
hmmm doesn't work for me. Is there an example?

**Comment by naiba** [comment]
I use https://github/gophers/xgo , support go mod, local repo.2019年8月14日 02:36，Cédric Verstraeten <notifications@github.com>写道：hmmm doesn't work for me. Is there an example?
